# Generated by Django 3.1.4 on 2023-05-12 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='fnames',
        ),
    ]
